### ISSUE TITLE
Reliable Data Channels?

### ISSUE THREAD

**Issue by D1plo1d** [lerouxrgd/datachannel-rs#1]
Does this crate support reliable unordered mode data channels?

**Comment by lerouxrgd** [comment]
It will very soon, stay tuned !

**Comment by D1plo1d** [comment]
Very exciting!

**Comment by lerouxrgd** [comment]
This has been added in `0.1.2`. 

You can now define a `Reliability` struct that should be passed to `RtcPeerConnection::create_data_channel_ext`. In your case that would be `Reliability::default().unordered()` (see an example in `tests/websocket.rs`).

Let me know if that works for you.

**Comment by D1plo1d** [comment]
Wow, yes, that looks great, Your a bit ahead of me on this one - I'm about a third of the way through porting my 3D printing over WebRTC app ( https://tegapp.io ) from NodeJS to Rust and the WebRTC connection will have to be the last to be ported but I am very excited to give this a go once I've gotten out from under my pile of Rust porting. Thanks so much!
