### ISSUE TITLE
Add RtcPeerConnection::local_description

### ISSUE THREAD

**Issue by manifest** [lerouxrgd/datachannel-rs#10]
In some cases it's useful to get the [current local description](https://github.com/paullouisageneau/libdatachannel/blob/master/src/peerconnection.cpp#L105-L108) containing all the ice candidates gathered at the moment.

**Comment by lerouxrgd** [comment]
Added in `0.3.1`.

**Comment by manifest** [comment]
Thanks.

Shouldn't it be of `SessionDescription` type?
It seems as there is some inconsistency with the WebRTC [spec](https://www.w3.org/TR/webrtc/#dom-rtcsessiondescription) and between setters (`set_remote_description`) and getters (`remote_description`, `local_description`) in the implementation.

**Comment by lerouxrgd** [comment]
Good point.

**Comment by manifest** [comment]
It looks perfect now :-) Thanks.

Do you mind making [fmt_sdp and serde_sdp](https://github.com/lerouxrgd/datachannel-rs/blob/8a31a5ccc1b42e9e765ef8e6cab10d13ff4eaedc/src/peerconnection.rs#L96-L124) public? This way it will be possible to serialize  just the sdp field of the `SessionDescription`. It gets helpful where `sdp_type` is already defined by an API.

**Comment by lerouxrgd** [comment]
This has been released in `0.4.0`.
