### ISSUE TITLE
Build script seems to be building libdatachannel twice with the `static` feature enabled

### ISSUE THREAD

**Issue by JRF63** [lerouxrgd/datachannel-rs#29]
If I'm not misreading it, [this one](https://github.com/lerouxrgd/datachannel-rs/blob/180974ee26ea7c74e23b3b40f25fce6fee8d18aa/datachannel-sys/build.rs#L58) would still run after the first [`config.build();`](https://github.com/lerouxrgd/datachannel-rs/blob/180974ee26ea7c74e23b3b40f25fce6fee8d18aa/datachannel-sys/build.rs#L35). Is that intentional?

I was [working](https://github.com/JRF63/datachannel-rs/blob/windows-static/datachannel-sys/build.rs) (not yet ready for a PR) on making the `static` feature work on Windows when I noticed I have both `datachannel.lib` and `datachannel-static.lib` inside `OUT_DIR/lib/Debug`.

**Comment by lerouxrgd** [comment]
Yes because the first one has `config.build_target("datachannel-static");`

**Comment by JRF63** [comment]
Yes, but exactly one of them is being linked. Why build the shared library too? I had the tests working with just the one for `datachannel-static`.

**Comment by lerouxrgd** [comment]
If I remember correctly `config.build_target("datachannel-static")` will build only `datachannel-static`, so you still need to build all other static libs (usrsctplib, etc) in order to link them.

It's possible that libdatachannel's CMake files have changed since I made this build.rs though, I'll try to write a CI that checks all that.

**Comment by JRF63** [comment]
It does only build that. The code path is just hitting both:
```rust
#[cfg(feature = 'static')]
{
    // static
}

// shared
```

instead of
```rust
if cfg!(feature = 'static') {
    // static
} else {
    // shared
}
```
or
```rust
#[cfg(feature = 'static')]
{
    // static
}

#[cfg(not(feature = 'static'))]
{
    // shared
}
```

I'm closing this for now, thanks for your time. I just saw it while doing a fix for handling CMake if it auto-chooses Visual Studio or XCode.
