### ISSUE TITLE
Cannot build on windows

### ISSUE THREAD

**Issue by vanlueckn** [lerouxrgd/datachannel-rs#36]
I cannot build this on windows (with cargo build). The compiler does not find my openssl installation. I have openssl installed.

**Comment by lerouxrgd** [comment]
Hello,

Did you have a look at the Windows [CI](https://github.com/lerouxrgd/datachannel-rs/blob/master/.github/workflows/ci-dynamic.yaml) ?
It actually builds and works fine for Windows. Is your setup different ?

**Comment by vanlueckn** [comment]
Hi,

i uninstalled openssl and installed the same version as in the build script (also with choco). I still get this error when running `cargo b`:

![Code_9BXxxM4Une](https://github.com/lerouxrgd/datachannel-rs/assets/53119369/5478982e-9a3d-4e1f-9b08-a71af77825c0)

**Comment by vanlueckn** [comment]
I simply copied the instructions from the Windows CI, now the build works.
