### ISSUE TITLE
Compatibility with browser implementations

### ISSUE THREAD

**Issue by manifest** [lerouxrgd/datachannel-rs#7]
Does this crate aim to be compatible with browser implementations?

I've just noticed that
- Serialization of the SessionDescriptor struct produces an object with [desc_type](https://github.com/lerouxrgd/datachannel-rs/blob/780bdea0dfd5acfc7861cf9d8f4137f9d8e8adb2/src/peerconnection.rs#L92) property instead of [type](https://www.w3.org/TR/webrtc/#dom-rtcsessiondescription).
- Serialization of the IceCandidate struct produces an object with [mid](https://github.com/lerouxrgd/datachannel-rs/blob/780bdea0dfd5acfc7861cf9d8f4137f9d8e8adb2/src/peerconnection.rs#L158) property instead of [sdpMid](https://www.w3.org/TR/webrtc/#dom-rtcicecandidate).

**Comment by lerouxrgd** [comment]
Thank you for point that out, it's good thing to keep the same naming indeed.
I fixed it on master and it will be available in the next release.

As for deeper browser compatibility I will soon investigate how to seamlessly use the current API with different underlying implementation based on the compilation target:
- target wasm -> use wasm-bindgen generated types
- target native -> use libdatachannel

**Comment by manifest** [comment]
What about user agents like Firefox or Chrome? I wonder if libdatachannels were tested against their implementations.

**Comment by paullouisageneau** [comment]
@manifest Yes, libdatachannel is compatible with both Firefox and Chrome.

**Comment by manifest** [comment]
@paullouisageneau Thanks for clearing this up. Is there any example (in cpp any other language) that I can check out. I wasn't able to make any of the browser work with the current implementation yet.

**Comment by paullouisageneau** [comment]
Sure, you can find C++ examples here: https://github.com/paullouisageneau/libdatachannel/tree/master/examples

In particular, `client`and `web` examples can connect together.

**Comment by lerouxrgd** [comment]
Note that this corresponds roughly to the `websocket.rs` test here.

**Comment by manifest** [comment]
I was able to create a connection between a browser and a native app. Thanks.

**Comment by billyb2** [comment]
@manifest I'm trying to build to the WASM target, but I get this error:

```
  In file included from apps/app_rand.c:10:
  In file included from apps/apps.h:13:
  In file included from ./e_os.h:16:
  In file included from include/openssl/e_os2.h:243:
  /usr/lib/clang/11.1.0/include/inttypes.h:21:15: fatal error: 'inttypes.h' file not found
  #include_next <inttypes.h>
                ^~~~~~~~~~~~
  1 error generated.
  make[1]: *** [Makefile:680: apps/app_rand.o] Error 1
  make: *** [Makefile:177: build_libs] Error 2
  thread 'main' panicked at '


  Error building OpenSSL:
      Command: "make" "build_libs"
      Exit status: exit status: 2

```

Do you have any advice?

**Comment by manifest** [comment]
Hey @billyb2,

I haven't had a need to build the library for the WebAssembly target.
IMO the browser's WebAPI is a more natural choice.

**Comment by lerouxrgd** [comment]
@billyb2 this library is not meant to be compiled in wasm as-is. As @manifest mentioned the browser API should be used instead, here is an [example for datachannel](https://rustwasm.github.io/docs/wasm-bindgen/examples/webrtc_datachannel.html).

So for this library this would mean to use a different backend implementation based on the compilation target (while keeping the same public API): if the compilation target is wasm then use `wasm-bindgen` backend, otherwise use `libdatachannel` backend. 

I have been working on a `wasm-bindgen` backend to achieve this, however it would break the current public API as it requires some methods to be `async`. So I have not released it yet and it is still work in progress.

**Comment by billyb2** [comment]
Thank you both very much!
